### ISSUE TITLE
Bugs no Responsivo

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#100]
- [x] Tirar linha da Home, deixar só o do cérebro até Software
- [x] Carossel de cursos está com problemas (resolvido na #80)
- [ ] FAQ -> diminuir fonte proporcionalmente, ainda está muito grande, o ideal seria diminuir o suficiente para evitar linha dupla

Exemplos das issues:
![screen shot 2016-01-26 at 18 00 30](https://cloud.githubusercontent.com/assets/5922977/12625268/2b1ff86e-c51a-11e5-8236-ddf3f06abc01.png)
![screen shot 2016-01-26 at 18 01 54](https://cloud.githubusercontent.com/assets/5922977/12625271/2b729b0a-c51a-11e5-9d37-daad8e1e8784.png)
![screen shot 2016-01-26 at 18 02 44](https://cloud.githubusercontent.com/assets/5922977/12625270/2b63695a-c51a-11e5-885d-8b3f1b6b9f0a.png)

**Comment by ariadnemelo** [comment]
@luisfbs pra terceira opção ser possível (deixar o texto sem quebra de linha) só se tirarmos os ícones de + e -

**Comment by luisfbs** [comment]
@ariadnemelo Acho que assim fica mais fácil então, em relação ao FAQ

arquivos png necessários: https://drive.google.com/open?id=0BzwLqp3fsjJkMzlTUWtEZmZUblU

Antes: ![faq-antes](https://cloud.githubusercontent.com/assets/5922977/12651700/d2dbed42-c5ce-11e5-8dc0-47e160d18820.jpg)

Depos: ![ex-faq-melhorado](https://cloud.githubusercontent.com/assets/5922977/12651648/9102349e-c5ce-11e5-88f0-29cee604d270.jpg)

1. Alinhar os textos todos com a primeira letra após o numerador;
2. Usar novos ícones, tanto no desk quanto no responsivo, arquivos no drive;
3. Diminuir o espaçamento vertical entre a resposta e a pergunta;
4. Diminuir caixa da pergunta de forma a manter a mesma distância entre a linha de topo e a pergunta e a linha de baixo;

**Comment by ariadnemelo** [comment]
@luisfbs "Alinhar os textos todos com a primeira letra após o numerador"
eu consigo alinhar o texto da reposta mas o texto da pergunta como está no exemplo não é possível

o texto da pergunta (incluindo a numeração) vem do admin, ou seja, é um texto corrido, eu não consigo mudar o posicionamento da segunda linha em diante para alinhar desse jeito

**Comment by luisfbs** [comment]
@ariadnemelo beleza, vamos seguir apenas com a resposta alinhada, obrigado.

**Comment by ariadnemelo** [comment]
@luisfbs acredito que agora está ok, só não fiz a alteração que comentei acima porque não é possível mesmo

**Comment by luisfbs** [comment]
@ariadnemelo eu exclui a demanda, melhor assim, obrigado
