### ISSUE TITLE
Responsivo - Notícias

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#103]
- [x] Não aparece o texto introdutório
- [x] Notícias -> NOTÍCIAS
- [x] Centralizar ícone com NOTÍCIAS
- [x] Diminuir mais a fonte das manchetes em cima das fotos e talvez esconder mais o texto de descrição da primeira notícias
- [x] Manchetes sobre as fotos: posicionar os títulos no canto inferior, mantendo no topo as categorias apenas

![screen shot 2016-01-27 at 17 33 58](https://cloud.githubusercontent.com/assets/5922977/12625862/cba1d3dc-c51c-11e5-81bc-89b412bc1820.png)
![screen shot 2016-01-27 at 17 34 02](https://cloud.githubusercontent.com/assets/5922977/12625861/cba13ed6-c51c-11e5-9029-49b93cc19c1b.png)

**Comment by ariadnemelo** [comment]
@luisfbs "Não aparece o texto introdutório" tem que ver com alguém de back-end

**Comment by luisfbs** [comment]
@ariadnemelo 

1. Qual a pessoa mais indicada, Bruno ou Rafa, em termos de Backend?
2. Esconder mais o texto era uma ideia para tentar que o texto (exemplo logo abaixo)
 não ficasse cobrindo tanto a foto, então se um texto diz "Hey1, hey2, hey3 ,hey4, hey5." o novo texto diria "Hey1, hey2, hey3 [mais...]". 
![exe-texto-foto](https://cloud.githubusercontent.com/assets/5922977/12649971/25aa6d48-c5c8-11e5-9342-1539e0c4d542.jpg)
3. Acredito que possa ser difícil, mas eu pensei nisso tomando em conta que alguns sites conseguem fazer isso: 
![exemplog1](https://cloud.githubusercontent.com/assets/5922977/12650003/46faf2e2-c5c8-11e5-844b-e32876be1c2a.jpg)

**Comment by ariadnemelo** [comment]
@luisfbs melhor você falar com o bruno e aí ele vem quem está disponível para fazer, eu acho

sobre o texto de descrição: ele já está configurado para esconder uma parte, certo, é por isso que aparecem as reticências "[...]" não sei se dá para configurar um número de palavras no mobile e outro no desktop, tem que ver com alguém de back end

**Comment by luisfbs** [comment]
@ariadnemelo beleza, então, como eu falei no slack, vamos eliminar o texto de resumo do primeiro destaque, todos os destaques no responsivo vamos deixar apenas as manchetes, tentar melhor o rate/proporção de diminuição do tamanho de fonte, e alinhar mais abaixo.

E também tem, como eu reparei, a issue de não estar aparecendo os boxes coloridos das tags.

Valeu.

**Comment by ariadnemelo** [comment]
@luisfbs sobre a cor da tag/categoria:

o código que mostra a categoria é o seguinte `<span class="post-category" style="background:<?php echo $cat_bg; ?>"><?php _cat() ?></span>`

por algum motivo não está imprimindo a cor da categoria (no html do site o background aparece vazio)

**Comment by ariadnemelo** [comment]
@luisfbs resolvi todos os problemas de layout, sobre essas outras pendências acho melhor criar issues específicas para elas senão elas vão se perder nos comentários

**Comment by luisfbs** [comment]
@ariadnemelo beleza, vou fazer com o @elvis aqui
