### ISSUE TITLE
Responsivo - Explore a Plataforma

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#104]
- [x] Tem texto em amarelo
- [x] A imagem da página não parece obedecer à diminuinção proporcional do responsivo

![screen shot 2016-01-27 at 17 32 56](https://cloud.githubusercontent.com/assets/5922977/12625898/fba99b28-c51c-11e5-9833-eeacf11d2bcf.png)

**Comment by ariadnemelo** [comment]
**"Tem texto em amarelo" **ok, mas o que é para ser feito com esse texto?

**Comment by luisfbs** [comment]
O texto parece ser um teste de legenda, ele lê "Esta é uma citação de exemplo que pode ser usada. Pelo editor!"
Pode apagar, @ariadnemelo
