### ISSUE TITLE
Responsivo - Menu

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#105]
- [x] <li> com padding de 12px / proporcional tal como no exemplo, para aumentar a área de clique
- [x] quando a categoria está aberta, a seta aponta para cima, se possível
- [x] adicionar a categoria login/logout (quando for implementado)

![screen shot 2016-01-27 at 18 51 43](https://cloud.githubusercontent.com/assets/5922977/12628015/3866c15c-c528-11e5-9fa2-6c93aebf8d11.png)

**Comment by ariadnemelo** [comment]
@luisfbs fiz os ajustes mas sobre os itens de login e logout eu creio que vou precisar do layout de como eles vão ficar no mobile

**Comment by luisfbs** [comment]
@ariadnemelo beleza
