### ISSUE TITLE
Correção do Header

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#106]
#### Elvis ou Ariadne, vou colocar os links para vocês poderem verificar direto, se não perco muito tempo tirando print-scren:

- [x] Conheça Tim Tec http://timtec.hacklab.com.br/pt/conheca-timtec/ :: a altura do header deve seguir os mesmos padrões de outras páginas que tem texto, como Notícias http://timtec.hacklab.com.br/pt/lista-de-noticias/ e Lista de Cursos http://timtec.hacklab.com.br/pt/lista-de-cursos/, inclusive diminuindo as fontes para 1em
- [x] Implementar header de Sobre em: O que são Moocs http://timtec.hacklab.com.br/pt/o-que-sao-moocs/ e Conselho Consultivo http://timtec.hacklab.com.br/pt/conselho/
- [x] Implementar header de Software em Instale Agora http://timtec.hacklab.com.br/pt/download/ Manuais da Plataforma http://timtec.hacklab.com.br/pt/manuais/ e Desenvolva o Software http://timtec.hacklab.com.br/pt/desenvolva-o-software/
- [x] Implementar header de Rede em Faq http://timtec.hacklab.com.br/faq, e Suporte http://timtec.hacklab.com.br/pt/suporte/
- [x] Implementar imagem do header de Contato http://timtec.hacklab.com.br/pt/contato/
tal como em
![ly01-nwheader-contato](https://cloud.githubusercontent.com/assets/5922977/12654958/b1de30be-c5dd-11e5-8ce7-975a889f3b19.jpg)
arquivo em https://drive.google.com/open?id=0BzwLqp3fsjJkMzlTUWtEZmZUblU

**Comment by luisfbs** [comment]
- [ ] Na página de Detalhes do Curso http://timtec.hacklab.com.br/course/introducao-a-criacao-de-sites/ em vez de estar [Detalhes do Curso], está {Detalhes do Curso}, trocar por favor

**Comment by luisfbs** [comment]
@ariadnemelo ou @ElvisBM  vocês sabem porque o CSS aparentemente não está puxando os outros pesos da Open Sans?

**Comment by ariadnemelo** [comment]
@luisfbs a font está sendo chamada na header, acho que o melhor seria incorporá-la aos arquivos do projeto, vou abrir uma issue pra isso
