### ISSUE TITLE
Melhoria Faq versão web

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#107]
- [ ] Alinhar texto de resposta com a pergunta
- [ ] Ver com a @ariadnemelo pois ela implementou no css os ícones de mais e menos, se não estiver implmentando na versão web, implementar

![faq-web-melhoria](https://cloud.githubusercontent.com/assets/5922977/12655334/96e9b8a8-c5df-11e5-9c42-b7aa72b7ac4f.png)

arquivos: https://drive.google.com/open?id=0BzwLqp3fsjJkMzlTUWtEZmZUblU

**Comment by ariadnemelo** [comment]
essas alterações já foram feitas na issue #100 

a versão desktop e mobile do site é a mesma, as mudanças acontecem por media query, mas coisas como os ícones por exemplo permanecem os mesmos

**Comment by luisfbs** [comment]
@ariadnemelo fechamos a issue, então? acho que é isso, né?

**Comment by ariadnemelo** [comment]
@luisfbs sim, vou fechar
