### ISSUE TITLE
Responsivo - Tablet - Background Images :: Header

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#116]
#### Duas opções, podem me procurar para discutirmos isso @ElvisBM, @brunosmartin e @ariadnemelo:

1. Eliminar as imagens do header no responsivo do tablet
2. Diminuir as imagens de fundo, talvez usando essa propriedade http://www.w3schools.com/cssref/css3_pr_background-size.asp

(outra opção possível seria eu criar imagens novas com menos elementos para esses headers, não seria difícil)

![screen shot 2016-01-29 at 14 33 49](https://cloud.githubusercontent.com/assets/5922977/12681890/f6e6ff78-c697-11e5-8187-35d0bd7b8f9b.png)
![screen shot 2016-01-29 at 14 35 00](https://cloud.githubusercontent.com/assets/5922977/12681891/f6e8c628-c697-11e5-9159-f23db86d32fe.png)

**Comment by ariadnemelo** [comment]
@luisfbs a primeira opção é a mais fácil, atualmente as imagens no header só aparecem em telas com largura maior que 768px, eu posso mudar para esconder em tablets, elas apareceriam somente em telas com largura maior que 992px, pode ser?

**Comment by luisfbs** [comment]
@ariadnemelo pode sim!
