### ISSUE TITLE
Responsivo - Tablet - Footer

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#117]
O footer não aparece no responsivo do tablet

![screen shot 2016-01-29 at 14 33 36](https://cloud.githubusercontent.com/assets/5922977/12682002/8ce03b2a-c698-11e5-9935-7b0801eb1beb.png)

**Comment by ariadnemelo** [comment]
@luisfbs seguindo o grid do Bootstrap o footer aparece apenas em resoluções com larguras maiores do que `768px`, aí depende de qual tablet estamos falando, o problema de fazer o footer aparecer em resoluções menores do que isso é que também vai aparecer para alguns dispositivos de celular

o menor breakpoint do Bootstrap é `480px`, posso deixar o footer aparecendo dessa largura de tela em diante ou criar um breakpoint específico para ele (que aí nós vamos precisar sentar e ver qual é o melhor), só que para isso também precisaria ser pensado um layout pro footer pra uma tela tão pequena
