### ISSUE TITLE
Implementar form de cadastro do Usuario 

### ISSUE THREAD

**Issue by ElvisBM** [hacklabr/portal-timtec#119]
Implementar o form de cadastro do Usuario  refs #91

**Comment by luisfbs** [comment]
##### Referente à tela de recepção pós-cadastro
@ElvisBM 
![ly04-nwcadastro-finalizacao](https://cloud.githubusercontent.com/assets/5922977/12820228/57455426-cb45-11e5-80ec-ad6dd7bcfcd5.jpg)
