### ISSUE TITLE
Header de Notícias 

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#128]
##### Notícias - home

- Antes estávamos sem o texto de abertura, agora temos, legal, mas aparecem umas markings que eu não entendo o que estão fazendo lá, reparem no início e no fim a presença de barra e aspas: /";
- A imagem do header desapareceu;
- Temos que corrigir o destaque menor da direita, que tem altura maior que o da esquerda;

##### Como está atualmente
1. Header sem imagem
![screen shot 2016-02-05 at 16 19 46](https://cloud.githubusercontent.com/assets/5922977/12855198/2b63c62c-cc25-11e5-848a-db9824332b66.png)

2. Altura diferente dos destaques
![screen shot 2016-02-05 at 16 19 58](https://cloud.githubusercontent.com/assets/5922977/12855206/376ec886-cc25-11e5-9017-f474bdc0c680.png)

##### Layout tal como foi proposto
![ly05-nwnews](https://cloud.githubusercontent.com/assets/5922977/12855212/4922d0e0-cc25-11e5-8e85-4eb9043a7930.jpg)

**Comment by ariadnemelo** [comment]
@luisfbs @bruno eu só não sei como corrigir o texto do header, a função do CTRL pra editar não está funcionando aqui para mim

se alguém souber como corrigir por favor me avise

**Comment by ariadnemelo** [comment]
corrigido o texto, estava no post type Notícias, em Destaques
