### ISSUE TITLE
Menu Mobile

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#129]
##### Menu responsivo

- [x] Devolver a seta que indica que certas opções do menu escondem outros contextos referentes àquela categoria;
>> Não podemos nos dar ao luxo de pensar que o cara provavelmente usou a versão web/desk e sabe que funciona desta forma<<

- [x] Implementar corretamente a opção de login, quando o usuário estiver logado ele só poderá ter o menu como controle do fato de ele estar logado, uma vez que assim como hoje aparece o avatar com as inicias dele na versão web/desk, com o feedback "Logado", no responsivo o mesmo comportamento será reproduzido. 

##### Isso porque como a Tim exige o logo do Instituto Tim, e que seria difícil talvez trabalhar esse menu para diminuir ainda mais o logo no responsivo e ganhar esse espaço para login, acho que essa é a melhor opção.

![mobile-menu](https://cloud.githubusercontent.com/assets/5922977/12857202/f19d0560-cc2f-11e5-9fb2-3625d590bac9.jpg)

**Comment by ariadnemelo** [comment]
@luisfbs acho que fiz os ajustes dos quais vc estava falando, depois pode dar uma olhada?

**Comment by luisfbs** [comment]
@ariadnemelo está tudo certinho, só duas coisas:
1.  a seta não vira pra cima com o submenu aberto, mas se isso for difícil, acho que pelo menos, tendo a seta indicando que há submenu já torna ele usável o suficiente
2. o login deveria ficar, no mobile, ao lado do avatar de usuário, e não abaixo, mas assim como a issue que eu expus acima, acho que está bonito e usável o suficiente, não precisa encanar com anda disso se for muito custoso.
De resto, tá lindo, valeu! =)
