### ISSUE TITLE
Listagem de Notícias

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#132]
- [ ] Implementar colunagem de tags;

Vamos esperar por elas decidirem os nomes dessas colunas, mas acredito que tendo a estrutura pronta, isso é o mais fácil; 

O psd encontra-se aqui: https://drive.google.com/open?id=0B4hadY-vSWEtRFBRS29EV0loM2M

![ly01-nwnews-listagem](https://cloud.githubusercontent.com/assets/5922977/12954011/fe8eb2b4-d003-11e5-8698-30c30c0aadf9.jpg)

**Comment by ElvisBM** [comment]
refs #131
