### ISSUE TITLE
Footer - Texto legal da licensa Creative Commons

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#133]
##### Referenciado a partir da issue #130 do @brunosmartin 

- [ ] Adicionar texto legal tal como no exemplo, tamanho de fontes e alinhamentos no arquivo PSD que está no Drive: https://drive.google.com/open?id=0B4hadY-vSWEtRFBRS29EV0loM2M

![ly01-nw-creativecommons-footer](https://cloud.githubusercontent.com/assets/5922977/12961378/530cd9e2-d027-11e5-95d5-3052c39ba7d9.jpg)

**Comment by ariadnemelo** [comment]
@ElvisBM elvis, o texto está hardcoded no arquivo footer.php, precisa colocar no esquema de tradução
