### ISSUE TITLE
Tablet Responsivo - CSS Triângulo dos modais

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#139]
###### Teste final em Ipad

No último teste feito, em tablet, não no navegador simulando o responsivo de um tablet, reparei que estamos com um problema de renderização do triângulo de diálogo dos modais.

Não sei se é um problema passível de resolução, mas creio que dado o cliente, devemos tentar encontrar alguma alternativa.

@ElvisBM @brunosmartin @rafaelchavesfreitas @ariadnemelo 

![img_0191](https://cloud.githubusercontent.com/assets/5922977/13010917/77705394-d18b-11e5-9e82-008b9bf967d3.jpg)

**Comment by ariadnemelo** [comment]
acho que no fim a solução vai ser fazer uma imagem do triângulo (com o dobro do tamanho para não desfocar em telas retina)

**Comment by luisfbs** [comment]
@ariadnemelo também pensei nisso, mas acredito que o melhor jeito é usar svg então, eu inclusive estava dando uma estudada porque acho que a gente poderia ter usado em outras porções do site, com ganhos de resolução e peso do arquivos loadados. 

Much to learn, young padawan. =(

**Comment by ariadnemelo** [comment]
no caso desse triangulo um png não pesaria tanto porque é uma imagem chapada de apenas uma cor, deve ficar com alguns kb somente

mas em outros casos como temos muitas imagens que se repetem talvez seja uma boa estudar substituí-las por svg
