### ISSUE TITLE
Feedback La Fabbrica - Detalhe do Curso

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#150]
Homologação: http://timtec.hacklab.com.br/course/desenvolvimento-de-back-end/
Invision: https://invis.io/PB5RT115W

- [x] Subtítulo do Header, em vez de "[Detalhe do Curso]" -> "[Sobre o Curso]"
- [x] Trocar "Instituto" por "Instituição
- [x] Deixar as fontes de Instrutor e Instituição logo abaixo do título do curso igual ao que está no Invision;
- [x] O nome do instrutor e da instituição devem ser linkáveis (o instrutor para sua página, e a instituição para a página da instituição);
- [x] Colocar um texto falso em "Pré-Requisitos" e "Estrutura do Curso" para que elas possam avaliar os alinhamentos, bem como nos meta-dados da coluna menor da direita de "Aulas", "Vídeos" e "Nível";
- [x] Aplicar os mesmos estítilos de fonte, foto e descrição da coluna direita de "Instrutores em relação à aquilo que está no invision;

**Comment by ElvisBM** [comment]
@luisfbs  Instituição não tem página para ser linkada

**Comment by ElvisBM** [comment]
@luisfbs 0 5 item precisa só preencher dentro do Admin com dados falsos

**Comment by luisfbs** [comment]
Beleza, mas por exemplo se o curso do instituto federal do paraná, linka para o instituto federal do paraná, se for do timtec, talvez poderíamos conversar com elas, e aí deixar TimTec, e não linkar, ou usar algum outro termo como, exclusivo.

**Comment by luisfbs** [comment]
Pode popular a página com infos falsas
