### ISSUE TITLE
Feedback La Fabbrica - Lista de Curso e blocos de curso

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#152]
Invision: https://invis.io/WG620PG4K

- [ ] Criar uma padronização de distância dos botões "Assistir Aulas" e "Baixar Pacote" em relação à linha de "Instrutores", vamos conversar como seria possível fazer isso;
- [x] Cor do botão "Assistir Aulas" em rgba(0, 193, 179, 0.5) quando inativo, rgba(0, 193, 179, 1) quando ativo;
- [x] Cor do botão "Baixar Pacote" em rgba(255, 137, 105, 0.7) quando inativo, rgba(255, 137, 105, 1) quando ativo;

**Comment by ElvisBM** [comment]
@luisfbs  referente essa padronização você fala, deixar o tamanho da caixa de texto de instrutuores fixo e o botões fixo tbm, para ter o mesmo alinhamento?

**Comment by luisfbs** [comment]
sim!

**Comment by luisfbs** [comment]
Elvis, pode mandar bala nessa lista, segue o jpg:
![ly05-nwcurso-lines](https://cloud.githubusercontent.com/assets/5922977/13225086/1628e196-d96a-11e5-8055-d7f462cd22c8.jpg)

O psd encontra-se em https://drive.google.com/open?id=0B4hadY-vSWEtRFBRS29EV0loM2M

A configuração para a linha é rgba(255, 255, 255, 0.2)
