### ISSUE TITLE
Feedback La Fabbrica - Notícias - Home e Internas

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#153]
Invision: https://invis.io/NC620RL69
- [x] Na paginação "Todas as Notícias" e de notícias por **#Tag** , trocar o subtítulo para conjunção de caixa alta e baixar, desta forma: **#TODASNOTÍCIAS** lerá-se **#TodasNotícias**, e para tag, por exemplo **#CURSOS** deverá ler-se **#Cursos**;
- [x] Nos títulos das reportagens (dos destaques, e da paginação) -> font-weight:600 e aplicar -webkit-font-smoothing: antialiased; e -moz-osx-font-smoothing: grayscale;
- [ ] Adicionar um seguir no widget do Facebook;
- [x] Trocar cor do widget do Facebook para #3b5998;
- [x] Trocar **"Mais recentes"** por **"Últimas notícias"**;
- [x] Aplicar no botão **"Ver mais notícias"** o mesmo estílo do botão **"Iniciar sessão"** do modal de login, também atentar-se para ver se está alinhado à esquerda com o resto dos elementos da página (na meu chrome, não está);
- [x] Cor do filtro das fotos, vamos fazer um degradê que seja mais escuro embaixo só, e bem mais claro no topo do que está hoje, seguir exemplo do g1 http://g1.globo.com/index.html em que o degradê (que no portal deles é da esquerda para direita) termina com a cor original da foto;
- [x] Na Interna de Notícias, o **"Notícias"**, no header, deve estar linkado com a home;
- [x] **"Relacionados"** trocar por **"Notícias relacionadas"**, ainda, foi reparado que entre as notícias relacionadas exibidas no fim, está a própria notícia que está sendo visualizada, corrigir;
- [x] Título da Notícia na interna daquela notícia, seguir o mesmo padrão de estilo do título da notícia na home, como está já detalhado acima -> font-weight:600 e aplicar -webkit-font-smoothing: antialiased; e -moz-osx-font-smoothing: grayscale;

Outras issues:
1. @ElvisBM A Bruna falou que as tags estão sem **#** no ambiente de homologação;
2. @ElvisBM e @brunosmartin Ela gostaria que o resumo das notícias fosse editável, eu não sei responder se está ou não, responder aqui ou no rocketchat para eu poder passar para ela;
3. @ElvisBM elas estão reclamando do tamanho da caixa do facebook e das fotos, que não está igual ao que foi aprovado no layout, vamos conversar eu, você e o @brunosmartin para responder isso;
4. Elas queriam o tal da busca por notícias na home, @brunosmartin, você precisa entrar no invision e ler os comentários dessa página para podermos dar uma resposta mais técnica, que acho difícil que eu possa prover;

**Comment by ElvisBM** [comment]
@luisfbs  o Resumo da noticias pode ser editado direto no Wp-admin, no campo resumo.

**Comment by ElvisBM** [comment]
@luisfbs  referente ao widget do facebook é possivel colocar o curtir da página, porém acho que não ficará igual ao layout, pois acho que ou colocamos um novo widget acima só com essa funcionalidade ou trocamos o plugin do facebook, por um outro, porém é novamente uma pesquisa.

**Comment by ElvisBM** [comment]
@luisfbs  o campo de busca precisa ver com o @brunosmartin  se isso se encaixa no layout da home e criar o layout para essa tela

**Comment by ElvisBM** [comment]
@luisfbs  Lista de Possiveis Plugins, muitos deles apenas conseguimos colocar a Borda Azul e o Titulo Facebook

https://wordpress.org/plugins/easy-facebook-likebox/screenshots/

Versão Paga disponibiliza tudo: https://wordpress.org/plugins/custom-facebook-feed/screenshots/

Opção com Scroll: https://wordpress.org/plugins/facebook-by-weblizar/screenshots/

Configurações: https://wordpress.org/plugins/easy-facebook-page-feed/screenshots/

Opção: https://wordpress.org/plugins/advanced-facebook-wall-widget/screenshots/

Opção: https://wordpress.org/plugins/facebook-page-feed-graph-api/screenshots


@luisfbs  Verifica por favor as configurações e os Layouts, muitos deles não tem como mexer no interior pois ele puxa um iframe com as infos, como eu disse acredito que só conseguiriamos colocar a borda azul eo titulo Facebook

**Comment by brunosmartin** [comment]
Elvis,

Não vamos mudar o plugin não. Vamos fazer o que dá com este, e se não der
negociamos com o cliente.



Em 17 de fevereiro de 2016 12:24, Elvis Martins <notifications@github.com>
escreveu:

> @luisfbs <https://github.com/luisfbs> Lista de Possiveis Plugins, muitos
> deles apenas conseguimos colocar a Borda Azul e o Titulo Facebook
>
> https://wordpress.org/plugins/easy-facebook-likebox/screenshots/
>
> Versão Paga disponibiliza tudo:
> https://wordpress.org/plugins/custom-facebook-feed/screenshots/
>
> Opção com Scroll:
> https://wordpress.org/plugins/facebook-by-weblizar/screenshots/
>
> Configurações:
> https://wordpress.org/plugins/easy-facebook-page-feed/screenshots/
>
> Opção:
> https://wordpress.org/plugins/advanced-facebook-wall-widget/screenshots/
>
> Opção:
> https://wordpress.org/plugins/facebook-page-feed-graph-api/screenshots
>
> @luisfbs <https://github.com/luisfbs> Verifica por favor as configurações
> e os Layouts, muitos deles não tem como mexer no interior pois ele puxa um
> iframe com as infos, como eu disse acredito que só conseguiriamos colocar a
> borda azul eo titulo Facebook
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hacklabr/portal-timtec/issues/153#issuecomment-185227421>
> .
>



-- 
Bruno Martin
Hacklab/
11 2892 0122
11 3862 1186
