### ISSUE TITLE
Ajustar Fórum

### ISSUE THREAD

**Issue by gobbibruno** [hacklabr/portal-timtec#31]
Os boxes do Forum ficam sobrepostos quando a largura de tela é menor.

![design_quebrado_forum](https://cloud.githubusercontent.com/assets/15158985/11103290/b0b5a2fc-88a8-11e5-8b94-f89f21a622a3.png)

**Comment by ariadnemelo** [comment]
@brunosmartin tá ok na produção e acho que não é pra ter mesmo a sidebar? vou fechar qualquer abrimos outra issue pra verificar isso
