### ISSUE TITLE
Aumentar altura do título

### ISSUE THREAD

**Issue by gobbibruno** [hacklabr/portal-timtec#32]
O espaço entre header e a altura do título está pequena e precisa ser aumentada. Testei no Chrome e Firefox.

![altura_titulo](https://cloud.githubusercontent.com/assets/15158985/11103865/6f02a18a-88ac-11e5-9dd4-eff3ebc0dbd7.png)

**Comment by ariadnemelo** [comment]
@brunosmartin  só a página do faq que estava com problema, fora isso está ok na produção, falta fazer o release pra corrigir o título do faq
