### ISSUE TITLE
Aumentar espaço entre frase e "Faça uma pergunta"

### ISSUE THREAD

**Issue by gobbibruno** [hacklabr/portal-timtec#33]
Aumentar espaço entre frase e box "faça uma pergunta".

![space_faca_pergunta](https://cloud.githubusercontent.com/assets/15158985/11105563/d87cb628-88b6-11e5-9a72-7aee52f651de.png)

**Comment by ariadnemelo** [comment]
@brunosmartin tá ok no ambiente de teste, falta fazer um release
