### ISSUE TITLE
Inserir links para os Professores na página dos cursos

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#40]

**Comment by brunosmartin** [comment]
Tem um post type pra professores. Tem que criar um campo no curso para indicar o professor usando o link da página do professor.

**Comment by ElvisBM** [comment]
Já existe um campo "teachers" dentro do post type cursos que linka o professor ao curso dentro do curso, e já aparece na lista do curso, falta apenas a single do professor para colocar o link (refs #68 )
