### ISSUE TITLE
Implemetar single da questão do forum

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#45]
http://timtec.com.br/question/como-funciona-esse-projeto/

**Comment by ariadnemelo** [comment]
![timtec-single](https://cloud.githubusercontent.com/assets/2034550/11428403/36ebcd38-9452-11e5-926f-a8fdc19609e1.png)

tamanhos de font:

titulo: 24 px 
meta dados e autor: 12px
comments e outras dados de label: 15px

**Comment by ariadnemelo** [comment]
feito em https://github.com/hacklabr/portal-timtec/commit/add5f1e0f27dffb708f2ef3883e435bd27c9be44, https://github.com/hacklabr/portal-timtec/commit/b5fc36a734244413b78b08b3c0bdc197b5967f6b e https://github.com/hacklabr/portal-timtec/commit/4ede7652b1645c5eb6b31fb677b826e4e24b8367

@luisfbs quando puder dá uma olhada pra ver se está tudo ok?

**Comment by leandrodb** [comment]
@ariadnemelo @luisfbs @brunosmartin não esquecer que na produção vai precisar [configurar o plugin de forum](http://timtec.hacklab.com.br/wp-admin/edit.php?post_type=dwqa-question&page=dwqa-settings) para usar o template da pergunta assim como fiz agora no [ambiente de teste](http://timtec.hacklab.com.br/question/pergunta-de-teste/)

**Comment by brunosmartin** [comment]
Tem um "By" perdido ali. Colocar "por" usando a tradução do wordpress, e exibir "anônimo" se for usuário anônimo.

**Comment by ariadnemelo** [comment]
feito em https://github.com/hacklabr/portal-timtec/commit/32de0ab3c3d2e34fe15bee4700627190611a016f
