### ISSUE TITLE
Linha vertical prejudica a leitura no mobile

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#46]

**Comment by ariadnemelo** [comment]
o @luisfbs chegou a ver essa?

**Comment by luisfbs** [comment]
@brunosmartin @ariadnemelo 

Vamos retirar a linha do responsivo, a única linha que ficaria ativa é a do cérebro que segue até o primeiro box:
![screen shot 2016-01-15 at 17 29 08](https://cloud.githubusercontent.com/assets/5922977/12363012/8511b3d8-bbad-11e5-8146-721ddff01703.png)
