### ISSUE TITLE
Ajustar peso das fontes na home

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#47]
- [x] usar Teuton25 nos botões
- [x] aumentar o peso dos textos descritivos

**Comment by ariadnemelo** [comment]
@brunosmartin vi que é uma fonte paga e não tenho o arquivo, quem pode me passar?

**Comment by ariadnemelo** [comment]
feito em https://github.com/hacklabr/portal-timtec/commit/b6765e98e29819c622984e5f1591503e238bfb4f e https://github.com/hacklabr/portal-timtec/commit/5899e8688b99fc3744a82be6b5ac66c44c7ddab0
