### ISSUE TITLE
Botao BAIXAR CURSO e FAZER CURSO

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#48]
Fazer o botao no mesmo estilo do da home (box retangular, mesma proporcao).

Cores
Para o botao **fazer curso** quando ele estiver inativo usar o codigo #E67860
Com hover, usar a cor #FF8969
No clique podemos usar #CF6C56

Para o **baixar curso**
Vamos usar um azul fraco #a6b7da
Hover o azul original da home #4d70b5
E clique #3d5990

A ideia eh que o botao de **baixar curso** tenha menos visibilidade em relacao ao **fazer curso**, em vermelho, e eles operam de formas oposta, mais escuro para o mais claro, no primeiro caso, de fazer curso, e no de baixar, o hover produz uma cor mais forte. 

Vamos usar a mesma altura mas o width, assim que voce implementar, eu acerto.

Obs **vamos deixar sublinhado o leia mais, de forma que ele de a entender que eh um link/acao**

**Comment by luisfbs** [comment]
![timtec-luis](https://cloud.githubusercontent.com/assets/5922977/11380785/4ef4108a-92df-11e5-8257-fca21858747e.png)

Vamos alterar pra deixar assim.

Botao em visualização máxima (desktop), 120px de largura e ambos na mesma linha.
Vamos alterar a lógica, vamos deixar ambos os botões sem hover com a cor mais clara da paleta que eu enviei, e escurecerem no hover. Mas o botão baixar passa a ter uma cor mais clara ainda no modo inativo: #C5D1EA

Obrigado!

**Comment by ariadnemelo** [comment]
@luisfbs eu não sei se entendi bem sobre a troca de cores, mas depois você vê aí se está ok

também aproveitei pra ajeitar o responsivo da página que tava uma bagunça

**Comment by brunosmartin** [comment]
Falta corrigir botão para o firefox

**Comment by ariadnemelo** [comment]
corrigido
