### ISSUE TITLE
Linhas da home desconfiguradas e espaçamentos entres seções da home

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#49]
A linha de uma seção invade a outra seção, e fica por cima do ícone.

Verificar na proposta aprova se o espaçamento entre o fim de uma seção e o começo da ilustra da outra está correto

**Comment by ariadnemelo** [comment]
feito em https://github.com/hacklabr/portal-timtec/commit/aed8899217a6db4f24d1810d7476d67d7c0758a3
