### ISSUE TITLE
Mudar o texto do popup

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#53]
Parte de cima, em destaque: CLIQUE AQUI PARA ACESSAR OS CURSOS
com link para http://mooc.timtec.com.br

Em baixo, com fonte menor:
Este é o novo Portal TIM Tec. A plataforma TIM Tec mudou de endereço: mooc.timtec.com.br

**Comment by ariadnemelo** [comment]
@bruno feito em https://github.com/hacklabr/portal-timtec/commit/d126391d15d9f596da9465014c52b3313af69abd
aproveitei pra ajustar o responsivo dessa modal
