### ISSUE TITLE
Fontes do footer estão diferentes da home aprovada

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#54]
Compara com proposta do invision

**Comment by ariadnemelo** [comment]
@bruno acho que agora está ok, aproveitei pra ajustar outros probleminhas no layout

**Comment by brunosmartin** [comment]
Achei q tá diferente ainda.
https://projects.invisionapp.com/d/main#/console/4322761/115909164/preview
Na proposta a legibilidade tá melhor.
