### ISSUE TITLE
barra do wordpress ainda fica por cima do header na página do conselho

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#55]
http://timtec.com.br/pt/conselho/

**Comment by ariadnemelo** [comment]
@brunosmartin

tem algumas páginas que o wordpress não está imprimindo as tags do body

pelo o que eu naveguei aqui, além da página de conselho também as páginas abaixo estão com o mesmo problema

http://timtec.com.br/pt/lista-de-cursos/
http://timtec.com.br/pt/conheca-a-rede-tim-tec/

**Comment by ariadnemelo** [comment]
@bruno acho que agora está ok
