### ISSUE TITLE
Implementar tela de listagem de cursos

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#57]
https://projects.invisionapp.com/share/UA53S3QPT#/screens

Observe que tem 3 variações desta tela, mudando apenas o texto de destaque

Retirar o "Filtrar por áreas"

**Comment by ariadnemelo** [comment]
alterações do layout disponível em: https://drive.google.com/drive/u/0/folders/0B0Dk59dar170Vzh4cXpRYThiZm8
