### ISSUE TITLE
Fluxo de cadastro do usuário

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#58]
- [x] Definir papel padrão do usuário
- [ ] Pensar caminhos para a página de cadastro partindo do Fórum e da lista de cursos
- [x] Configurar straging e produção

**Comment by leandrodb** [comment]
Habilitei no admin Configurações > Geral (do meu local e do [staging](http://timtec.hacklab.com.br)) o registro que atribui o perfil mais básico, assinante, mas que o plugin de fórum permite postar perguntas então está ok. Se precisar o plugin tem uma configuração de permissões.
- Para criar um usuário, fiz o registro em uma aba anônima e habilitei o usuário como admin em outra aba, setando a senha para ele (porque não chegou email, acho que não está configurado no staging).
- [postei](http://timtec.hacklab.com.br/question/quero-fazer-um-curso-como-eu-faco/), mas o layout está quebrado. @ariadnemelo ? : )
