### ISSUE TITLE
Tornar o FAQ editável

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#60]
Avaliar plugin que a Carol gostou que é usado no AWC do Instituto TIM

**Comment by ElvisBM** [comment]
Transformar FAQ em página com shortcode ( [accordion][item title=""][/item][/accordion]).

**Comment by ElvisBM** [comment]
Sessões e textos serão colocados na pagina , issue #44 depende desta.

**Comment by ElvisBM** [comment]
Segue a URL da página de FAQ utilizando a mesma estrutura de post do awc.institutotim, com o shortcode de accordion e template FAQ
http://timtec.hacklab.com.br/pt/faq-shortcode/
