### ISSUE TITLE
implementar single de notícias

### ISSUE THREAD

**Issue by ariadnemelo** [hacklabr/portal-timtec#64]
layout em https://drive.google.com/drive/u/0/folders/0B0Dk59dar170WGVyY21qQTdKMFU

**Comment by luisfbs** [comment]
![ly02-nwsinglenews](https://cloud.githubusercontent.com/assets/5922977/12520167/19c52a6a-c12a-11e5-8b8c-edf48b551d2f.jpg)

* Novidades -> NOTÍCIAS
