### ISSUE TITLE
Validar imagens dos cursos para ficar na mesma resolução/tamanhos dos videos

### ISSUE THREAD

**Issue by ElvisBM** [hacklabr/portal-timtec#71]
Segue url de exemplo de vídeo e imagens de tamanhos diferentes, o youtube segue a proporção de largura:

http://timtec.hacklab.com.br/pt/lista-de-cursos/

**Comment by luisfbs** [comment]
Na minha opinião, há duas opções possíveis

1. Aumentar o *height* do vídeo: 
![video-maior](https://cloud.githubusercontent.com/assets/5922977/12362943/27055a4c-bbad-11e5-9a1a-52aca3da0b7b.png)
2. Diminuir a imagem dos cursos que não tem vídeo: 
![imagem-menor](https://cloud.githubusercontent.com/assets/5922977/12362957/383d57ce-bbad-11e5-9801-0beb736f8972.png)

**Comment by luisfbs** [comment]
Vamos com a opção 2. =)

**Comment by ariadnemelo** [comment]
só mudar a altura das imagens iria distorcer elas, uma vez que teríamos que manter a largura para não quebrar o grid

para evitar isso coloquei as imagens de fundo com um background-size cover
