### ISSUE TITLE
Avaliar se funcionamento do acordeon do FAQ faz sentido

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#72]
Quando vc "expande" uma questão do FAQ, todas as demais são encolhidas

**Comment by luisfbs** [comment]
Fiz uma análise do funcionamento e eu proponho o seguinte:

1. Todos os FAQs começam a interação fechados;
2. Cada FAQ só abre e permanece aberto a partir das decisões do usuário;

**Comment by brunosmartin** [comment]
@ElvisBM altere se necessário o funcionamento do acordeon de acordo com o comentário do @luisfbs

**Comment by ElvisBM** [comment]
@brunosmartin  Falei com o @luisfbs e conforme elas pediram seguindo o mesmo esquema do layout delas, e a nova forma de colocar a FAQ via shortcode.

http://timtec.hacklab.com.br/pt/faq-shortcode/
