### ISSUE TITLE
Ajustar responsivo de acordo com o guia

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/portal-timtec#80]

**Comment by ariadnemelo** [comment]
- [ ] tela de cursos
- [ ] tela de notícias
- [ ] tela sobre

**Comment by ariadnemelo** [comment]
@brunosmartin no layout que o @luisfbs enviou, aquela parte dos destaques da página sobre quando tem mais de um item vira um carousel, precisa pensar se isso é viável porque atualmente isso é um shotcode estático

**Comment by ariadnemelo** [comment]
@brunosmartin @ElvisBM precisa ver o que será feito com o menu no responsivo: como está aquela história do nav-walker para ele usar o menu padrão do Bootstrap?

**Comment by ariadnemelo** [comment]
@brunosmartin @ElvisBM eu tive que colocar o título do slide da página de cursos dentro da div do slide, ele aparece somente no mobile, mas o carousel do boostrap repete os elementos no fim do slide, alguma idéia de porque ele se comporta dessa forma? já tive esse problema antes no carousel de notícias e acho que alguém solucionou ele, acho que foi o @rafaelchavesfreitas ?
