### ISSUE TITLE
Header sem texto e Imagem para os headers de software

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#82]
Os arquivos estão no Drive das ilustrações estão em https://drive.google.com/open?id=0BzwLqp3fsjJkdG5mSWtCWmtyd2s

![ly01-nwheader-rede](https://cloud.githubusercontent.com/assets/5922977/12590275/38dbb960-c449-11e5-8dcb-2ef53cb35db3.jpg)
![ly01-nwheader-software](https://cloud.githubusercontent.com/assets/5922977/12590276/38fcab0c-c449-11e5-99eb-72de928e0bd4.jpg)
![ly01-nwheader-contato](https://cloud.githubusercontent.com/assets/5922977/12590779/bf7625f8-c44b-11e5-9bdb-443368de80b2.jpg)
![ly01-nwheader-sobre](https://cloud.githubusercontent.com/assets/5922977/12590867/4a35eb74-c44c-11e5-9edf-5e39e3ba860c.jpg)

**Comment by ariadnemelo** [comment]
@luisfbs esse alinhamento do texto seguindo a imagem que está no banner não tem como ser feito, minha sugestão é diminuir a imagem proporcionalmente para não vazar da área do banner

**Comment by luisfbs** [comment]
@ariadnemelo eu refiz ambas as propostas de header, segue ali em cima na descriação da issue

**Comment by ariadnemelo** [comment]
@luisfbs pode por favor me passar as ilustrações em png? preciso das páginas sobre, rede e software, tanto a versão normal quanto a sem texto

a única página feita até então é a página sobre com o header com texto, as outras páginas nem foram me passadas

obrigada

**Comment by ariadnemelo** [comment]
acho que agora está tudo ok, criei o template da página de contato que estava faltando, agora tem cabeçalho como as outras
