### ISSUE TITLE
Implementar NavWalker no menu do site

### ISSUE THREAD

**Issue by ariadnemelo** [hacklabr/portal-timtec#85]
o menu do site está quebrado no mobile, como o projeto usa bootstrap, o ideal seria usar o menu do bootstrap que já é responsivo e otimizado para mobile

https://hacklabr.slack.com/archives/timtec-hacklab/p1446674281000968

http://stackoverflow.com/questions/32258273/how-to-integrate-wp-nav-menu-wordpress-with-bootstrap-dropdown-menu-layout

**Comment by ElvisBM** [comment]
@ariadnemelo é para seguir esse  padrão do boostrap?

http://getbootstrap.com/javascript/#dropdowns
