### ISSUE TITLE
Novo Pop-up da Home - Página de cursos

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#86]
Os novos pop-ups, exceto um, utilizam uma versão do título do TimTec enquanto logo (esses arquivos estão todos no Google Drive):
![logo-timtec-pop-up](https://cloud.githubusercontent.com/assets/5922977/12454881/7ffb248e-bf80-11e5-8bec-8455d2ccd529.png)

Eles também envolvem o uso de um triângulo como se fosse um diálogo: https://css-tricks.com/examples/ShapesOfCSS/

Esse é o modelo do layout
![home_popup](https://cloud.githubusercontent.com/assets/5922977/12454847/5f101c5c-bf80-11e5-9d71-3a8229327bcb.png)

**Comment by ariadnemelo** [comment]
@brunosmartin @luisfbs falta só testar

**Comment by luisfbs** [comment]
Opa, tudo bem @brunosmartin, @ariadnemelo 
Eu estava dando uma passada agora de tarde para ver como andam as novas mods no site, e percebi que no firefox o triângulo do pop-up aparece serrilhado, detalhe aqui: 
![screen shot 2016-01-21 at 19 00 17](https://cloud.githubusercontent.com/assets/5922977/12494422/3d43df22-c071-11e5-8a8e-72866929a692.png)

Procurando para saber melhor sobre o problema, eu descobri que o firefox tem uma issue que segue, aparentemente, desde 2012: https://bugzilla.mozilla.org/show_bug.cgi?id=805393

Eu encontrei uma solução relativamente simples, o setting no css está colocado no campo de elemento, como vocês podem ver aqui:
![screen shot 2016-01-21 at 18 57 29](https://cloud.githubusercontent.com/assets/5922977/12494471/7757fe1e-c071-11e5-88e4-fac7583dad10.png)

Acredito que podemos adicionar esse setting em todos os códigos referentes a esse modelo de modal, uma vez que esse setting não altera em nada a visualização no Chrome, exemplo aqui: 
![screen shot 2016-01-21 at 19 03 38](https://cloud.githubusercontent.com/assets/5922977/12494520/c6f08fd6-c071-11e5-81a5-ddac34b8d903.png)

**No entanto, esse setting {border-style: dotted dotted solid} parece acrescentar alguns pixels a mais na distância entre o modal e o logo do {TimTec}, esse é o único porém.

**Comment by ariadnemelo** [comment]
@luisfbs foi corrigido
