### ISSUE TITLE
Menu com novo campo: Login / Logado

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#88]
* Quando o usuário não está logado:
![novomenu-deslogado](https://cloud.githubusercontent.com/assets/5922977/12455246/dded3e14-bf81-11e5-9560-dbe42dfb7eba.jpg)

* Quando o usuário está logado, o círculo se torna um avatar: um circulo, de mesma medida, porém com as iniciais do usuário e o feedback que avisa que eles está logado:
![novomenu-logado](https://cloud.githubusercontent.com/assets/5922977/12455268/fd0ded02-bf81-11e5-8512-18cbd88fb99e.jpg)

* Como eu disse, o ícone encontra-se em https://drive.google.com/open?id=0BzwLqp3fsjJkRFZ6Y3lwYmFCb0E

**Comment by ariadnemelo** [comment]
foram adicionados os itens ao menu, estão hard-coded
