### ISSUE TITLE
Tela de Cadastro do usuário

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#91]
**ATENÇÃO: LEIA O COMENTÁRIO >> Novo fluxo, pois não há mais segunda etapa de cadastro**

**Fluxo do Cadastro** 

1. O usuário recebe o primeiro passo que consiste dos campos: **email**, **Nome Completo**, **Nome Publico** (nada mais que um user name) e **Senha**;
2. Ao completar o preenchimento ele tem duas opções: criar o usuário assim mesmo, ou prosseguir para a segunda etapa;
3. Qualquer uma das duas opções envolve como critérios exclusivos: **o preenchimento dos campos obrigatórios** (todos, nessa etapa), **validação por meio do captcha**;
4. Caso o usuário não preencha o captcha, ao tentar clicar no botão que leva para a segunda etapa, ou clicar no link que cria o usuário sem a segunda etapa, o site dá highlight (pode ser um scroll automático que centraliza o captcha, ou simplesmente seleciona o campo onde ele deveria escrever a validação);
5. Quando o usuário decide ir para a segunda etapa de cadastro **AINDA ASSIM O USER É CRIADO**, desta forma, mesmo que ele desista no meio da segunda etapa, ou feche o site, ou acabe a bateria, enfim, qualquer caso em que o segundo passo do cadastro seja interrompido, ainda assim o user é criado;

**Comment by luisfbs** [comment]
**ATENÇÃO**
* Não há mais segundo passo, há um passo único;
* Novo campo obrigatório: Cidade/Estado
* Novo campo não obrigatório: Instituição
* Nova ordem de campos: Nome Completo > Nome para visualização > Email > Cidade/Estado > Instituição > Senha
* Novo nome para Nome público -> Nome para visualização
![ly03-nwcadastro](https://cloud.githubusercontent.com/assets/5922977/12520810/ca89c682-c12d-11e5-8a12-d4d379ebe490.jpg)

**Comment by luisfbs** [comment]
Algumas mudanças a partir do Feedback de 27/01/2016
- [ ] Criar uma nova conta -> Criar uma conta
- [ ] Email - > E-mail
- [ ] Novo campo: Confirmar e-mail
- [ ] Criar usuário -> Criar conta

![ly03-nwcadastro](https://cloud.githubusercontent.com/assets/5922977/12624503/9570f0b4-c516-11e5-8aa8-97c7bdf5ce8f.jpg)

**Comment by ariadnemelo** [comment]
@brunosmartin @luisfbs @ElvisBM terminei o front da página de cadastro, só não coloquei o captcha pois como o @luisfbs falou o que está no layout é um placeholder

todas as alterações do fluxo de cadastro e login do usuário estão no branch `login-cadastro-usuario`
