### ISSUE TITLE
Implementar single de professores

### ISSUE THREAD

**Issue by ElvisBM** [hacklabr/portal-timtec#93]

**Comment by ElvisBM** [comment]
Esperar aprovação do cliente

**Comment by luisfbs** [comment]
Implementar a single de acordo com esse modelo novo:
![ly03-nwsingleprofessor](https://cloud.githubusercontent.com/assets/5922977/12518450/d629fa06-c11f-11e5-8608-575304d68fb7.jpg)

* Foto do professor aumenta
* Nome com fonte tamanho maior
* Subdivisão entre Nome e Biografia
* Estou colocando o psd no Drive.

**Comment by luisfbs** [comment]
PSD em https://drive.google.com/open?id=0BzwLqp3fsjJkdG5mSWtCWmtyd2s
e IMPORTANTE! **Lista de Cursos é, na verdade <Detalhes do Professor>**
