### ISSUE TITLE
Refinamento dos textos de Login/Logout

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/portal-timtec#97]
- [x] Centralizar Login e as barras da esquerda e da direita (ainda não vi a implementação, mas no meu layout original essa parte estava zoada e eu só vi agora);

- [x]  Texto do modal de login, fazendo um "call-to-action" para o usuário se cadastrar: 
> Clique aqui para fazer o cadastro. O cadastro permite acessar os fóruns e baixar os cursos. 

- [x]  Iniciar Sessão -> "S" em caixa alta/maísculo

- [x]  Email -> e-mail

- [x] Texto do modal de logout que permite o usuário editar seus dados: 

> Pessoal Tal, para editar seus dados de perfil, clique aqui. 

![home_v09_luis-login](https://cloud.githubusercontent.com/assets/5922977/12623325/b4e8f6fe-c510-11e5-9e44-bac181a990c6.jpg)
![ly03-nwcurso-login](https://cloud.githubusercontent.com/assets/5922977/12623326/b4ef7ab0-c510-11e5-9667-73b14a41d48b.jpg)
![ly03-nwcurso-logout](https://cloud.githubusercontent.com/assets/5922977/12623324/b4e6b5d8-c510-11e5-9fa6-a10d39a43b2c.jpg)

**Comment by ariadnemelo** [comment]
alterações feitas, lembrando que todas as alterações relativas ao fluxo de login e cadastro estão no branch `login-cadastro-usuario`
